### PR TITLE
Fix argument separations

### PR DESCRIPTION
**Pull request by gsuess**
# What❓

I have noticed a bug that make version 1.2.0 unusable with regards to AST parsing, where `AND(x=TRUE(),y=FALSE())` would be incorrectly considered as a syntax error.

This is because the concept of the `DelimitedExpressionListNode` was a bit hacky and confusing.

I have replaced this with a different solution, which also greatly simplifies the main reducer loop.

# Why 💁‍♀️

Because otherwise `parse()` will fail on some of our formulas.

# Todos before it can be reviewed

The things that need to be completed before this can be reviewed:

None

# Todos before it can be merged

The things that need to be completed before this PR can be merged:

None

### CODE REVIEW

**Comment by gsuess** [comment]
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/95)

**Review by sirJiggles — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/95)* status: all files reviewed, 2 unresolved discussions (waiting on @gsuess)

___
*[`src/ast/index.ts` line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/95#-NCKenuo5LH-XKZmH_Et:-NCKenuo5LH-XKZmH_Eu:b5bkh0z) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/40d275b5ab894c9d3a1b4be0eea33647c8395d3e/src/ast/index.ts#L3)):*
> ```XML
> export * from "./tokenize";
> export * from "./parse";
> export { separateNodes } from "./nodes/separate-nodes";
> ```

I don't see how this is being used. Maybe I am missing how the AST is finally consumed?
___
*[`src/ast/nodes/argument-list.ts` line 90 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/95#-NCKbCV54a_-IKx8A22c:-NCKbCV60ZQx7dJYFchH:b-gtcdhj) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/40d275b5ab894c9d3a1b4be0eea33647c8395d3e/src/ast/nodes/argument-list.ts#L90)):*
> ```XML
> }
> 
> export function getDelimitedExpressions(
> ```

I do not see where this is imported, I think it does not need to be exported

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/95)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @sirJiggles)

___
*[`src/ast/index.ts` line 3 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/95#-NCKenuo5LH-XKZmH_Et:-NCKmaH469TM60UXcV6a:b-p3u166) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/40d275b5ab894c9d3a1b4be0eea33647c8395d3e/src/ast/index.ts#L3)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

I don't see how this is being used. Maybe I am missing how the AST is finally consumed?
</blockquote></details>

I am agnostic to how it's consumed. It's an AST after all. You do AST stuff with it. I have not changed the AST structure design at all though (except for where it was not outputting what it was designed to output).
___
*[`src/ast/nodes/argument-list.ts` line 90 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/95#-NCKbCV54a_-IKx8A22c:-NCKnSiF4o6syydv-AVD:b-896fix) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/40d275b5ab894c9d3a1b4be0eea33647c8395d3e/src/ast/nodes/argument-list.ts#L90)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

I do not see where this is imported, I think it does not need to be exported
</blockquote></details>

Done.

**Review by sirJiggles — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/95)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @sirJiggles)

**Review by sirJiggles — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gsuess)

**Pull request merged**
