### PR TITLE
AST Parser

### PR DESCRIPTION
**Pull request by gsuess**
# What❓

Airtable Formula AST Parser (experimental)

# Why 💁‍♀️

We still handle a lot of plain string airtable forumalas. In order to understand which fiedls these formulas are referencing, we need to be able to reliable parse them.

# Todos before it can be reviewed

The things that need to be completed before this can be reviewed:

- [x] Add tests for bad syntax handling
- [x] Add tests for enclosed expressions
- [x] Merge base branch #93 

# Todos before it can be merged

The things that need to be completed before this PR can be merged:

None

### CODE REVIEW

**Comment by gsuess** [comment]
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)

**Comment by gsuess** [comment]
Sorry for long PR, but its a AST parser, hard to break it down further. Happy to jump on a call to do review.

**Review by vubogovich — CHANGES_REQUESTED** [review]
> Reviewed 25 of 33 files at r1, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: all files reviewed, 3 unresolved discussions (waiting on @gsuess)

*[a discussion](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwdNzq1VGs5JAzHhiD:-NBwdNzq1VGs5JAzHhiE:b-l20k6) (no related file):*
The most complex PR in Qualifyze org :) If you need thorough review, I recommend to request one review more as I'm lazy to check every line and feels unnecessary for an experimental feature with nice end-to-end parse tests.
Overall, the solution feels quite an overkill for the current use case if we need to know only the fields from the formula. A good regex will not be so precise but much simpler and probably good enough.

___
___
*[`src/index.ts` line 3 at r5](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwY5C39kLaai2CxGEW:-NBwY5C39kLaai2CxGEX:b-h9hfcq) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/bff86ff8a78204e725a4ff93713f956409f9a035/src/index.ts#L3)):*
> ```XML
> export * from "./schema";
> export * from "./compiler";
> export * from "./tokenize";
> ```

Isn't this a breaking change that exported members of `tokenize` module disappear from the top level of the package?

I.e. breaks existing imports `import { operatorMatcher } from '@qualifyze/airtable-formulator'`
___
*[`src/ast/nodes/argument-list.ts` line 46 at r5](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwZ26z2s2scERTGWRH:-NBwZ26z2s2scERTGWRI:bky1yn1) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/23617d26d4677e77af0c8d8ed5a42ae1667bfd9b/src/ast/nodes/argument-list.ts#L46)):*
> ```XML
>   return (
>     node.type === type && isEnclosedWithParenthesis(node)
>     // node.members.every((x) => isArgumentListMember(x))
> ```

Please comment why this commented code might be interesting for the code base, or remove the line.

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: all files reviewed, 3 unresolved discussions (waiting on @gsuess and @vubogovich)

___
*[`src/index.ts` line 3 at r5](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwY5C39kLaai2CxGEW:-NBwga1VCWvSZdHL8oc7:b-o76ii9) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/bff86ff8a78204e725a4ff93713f956409f9a035/src/index.ts#L3)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Isn't this a breaking change that exported members of `tokenize` module disappear from the top level of the package?

I.e. breaks existing imports `import { operatorMatcher } from '@qualifyze/airtable-formulator'`
</blockquote></details>

yes you are right, forgot about the tokenizer. I just put this line in as an afterthought, because i need parse() to convert it to `Formula` not an AST.

Good catch.
___
*[`src/ast/nodes/argument-list.ts` line 46 at r5](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwZ26z2s2scERTGWRH:-NBwgq43-E4Yt5SSRLUf:b7jl5d) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/23617d26d4677e77af0c8d8ed5a42ae1667bfd9b/src/ast/nodes/argument-list.ts#L46)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Please comment why this commented code might be interesting for the code base, or remove the line.
</blockquote></details>

Very good catch.

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: 29 of 35 files reviewed, 3 unresolved discussions (waiting on @gsuess and @vubogovich)

___
*[`src/index.ts` line 3 at r5](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwY5C39kLaai2CxGEW:-NC0HuCGCgS5pWiVROvL:bb6un1j) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/bff86ff8a78204e725a4ff93713f956409f9a035/src/index.ts#L3)):*
<details><summary><i>Previously, gsuess (Garik Suess) wrote…</i></summary><blockquote>

yes you are right, forgot about the tokenizer. I just put this line in as an afterthought, because i need parse() to convert it to `Formula` not an AST.

Good catch.
</blockquote></details>

Done
___
*[`src/ast/nodes/argument-list.ts` line 46 at r5](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwZ26z2s2scERTGWRH:-NC0Hryr0xPr6NEN8DdX:bb6un1j) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/23617d26d4677e77af0c8d8ed5a42ae1667bfd9b/src/ast/nodes/argument-list.ts#L46)):*
<details><summary><i>Previously, gsuess (Garik Suess) wrote…</i></summary><blockquote>

Very good catch.
</blockquote></details>

Done

**Review by vubogovich — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: all files reviewed, 2 unresolved discussions (waiting on @gsuess)

___
*[`src/index.ts` line 3 at r5](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwY5C39kLaai2CxGEW:-NC4Sam116zfqzULbqOu:b-rsupdx) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/bff86ff8a78204e725a4ff93713f956409f9a035/src/index.ts#L3)):*
`tokenize` is not the member used to be exported.
> breaks existing imports import { operatorMatcher } from '@qualifyze/airtable-formulator'
___
*[`src/ast/tests/parse.test.ts` line 2631 at r7](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NC4S8qQ9LVc1IkA1fhC:-NC4S8qQ9LVc1IkA1fhD:b-13d9g8) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/aa696d0ca993d8838ff67ca9df1e54e138bda2c4/src/ast/tests/parse.test.ts#L2631)):*
> ```XML
>     //     "IF(AND(name='Robert',age >= {minimum age} + 10), TRUE(), 'not robert or underage')"
>     //   )
>     // ).toMatchInlineSnapshot();
> ```

Looks like WIP.

**Comment by gsuess** [comment]
*[`src/ast/tests/parse.test.ts` line 2631 at r7](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NC4S8qQ9LVc1IkA1fhC:-NC4VNkSBKqzqzVwAohM:baiva7r) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/aa696d0ca993d8838ff67ca9df1e54e138bda2c4/src/ast/tests/parse.test.ts#L2631)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Looks like WIP.
</blockquote></details>

i hate large PR :see_no_evil: 

done

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: 33 of 35 files reviewed, 2 unresolved discussions (waiting on @vubogovich)

___
*[`src/index.ts` line 3 at r5](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwY5C39kLaai2CxGEW:-NC4VLcdBukECOFpVFKr:b-r1liow) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/bff86ff8a78204e725a4ff93713f956409f9a035/src/index.ts#L3)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

`tokenize` is not the member used to be exported.
> breaks existing imports import { operatorMatcher } from '@qualifyze/airtable-formulator'
</blockquote></details>

you are right, done

**Review by vubogovich — DISMISSED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: all files reviewed, 1 unresolved discussion (waiting on @gsuess)

*[a discussion](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwdNzq1VGs5JAzHhiD:-NC4_5Ps-qD6SJFEa6E0:bcchxut) (no related file):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

The most complex PR in Qualifyze org :) If you need thorough review, I recommend to request one review more as I'm lazy to check every line and feels unnecessary for an experimental feature with nice end-to-end parse tests.
Overall, the solution feels quite an overkill for the current use case if we need to know only the fields from the formula. A good regex will not be so precise but much simpler and probably good enough.
</blockquote></details>

Keeping this comment as blocking since `dev-people` was requested review as well and PR is on auto-merge. Feel free to discard it if thorough review is not needed.

___

**Review by jorgechiapello — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: all files reviewed, 4 unresolved discussions (waiting on @gsuess)

*[a discussion](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NC4rm9f4ToIU7Rsxey3:-NC4re9y39G8w4oLIKoP:b-7jkya8) (no related file):*
I'm going to post my some questions but keep reviewing

___
___
*[`Readme.md` line 104 at r8](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NC4erSG1Zg2lMgJy4XH:-NC4erSG1Zg2lMgJy4XI:bd63733) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/1abca1994ae3711e1d832ffad0b941d6f551a959/Readme.md#L104)):*
> ```Markdown
>       },
>       {
>         "type": "fieldReference"
> ```

Why in here there no field `value` with value `age`?
___
*[`Readme.md` line 107 at r8](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NC4ezqtBGzLIgHDU8sv:-NC4ezqtBGzLIgHDU8sw:b84ugbr) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/1abca1994ae3711e1d832ffad0b941d6f551a959/Readme.md#L107)):*
> ```Markdown
>       },
>       {
>         "type": "number"
> ```

Same in here, why the value `0` is not stated?

**Review by jorgechiapello — COMMENTED** [review]
> Reviewed 1 of 6 files at r6, 1 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: all files reviewed, 4 unresolved discussions (waiting on @gsuess)

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: 33 of 35 files reviewed, 4 unresolved discussions (waiting on @gsuess, @jorgechiapello, and @vubogovich)

___
*[`Readme.md` line 104 at r8](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NC4erSG1Zg2lMgJy4XH:-NC4uALw-MxTzL8vm76o:b-xclr1) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/1abca1994ae3711e1d832ffad0b941d6f551a959/Readme.md#L104)):*
<details><summary><i>Previously, jorgechiapello (Jorge Alberto Chiapello) wrote…</i></summary><blockquote>

Why in here there no field `value` with value `age`?
</blockquote></details>

as mentioned in the readme below

nevertheless its good to keep the value in the matcher for clarity.
___
*[`Readme.md` line 107 at r8](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NC4ezqtBGzLIgHDU8sv:-NC4uIiJAO-Vs4Gvp0iE:b-2guby3) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/1abca1994ae3711e1d832ffad0b941d6f551a959/Readme.md#L107)):*
<details><summary><i>Previously, jorgechiapello (Jorge Alberto Chiapello) wrote…</i></summary><blockquote>

Same in here, why the value `0` is not stated? 
</blockquote></details>

same here

**Review by vubogovich — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: all files reviewed, 4 unresolved discussions (waiting on @gsuess and @jorgechiapello)

**Review by jorgechiapello — APPROVED** [review]
> Reviewed 17 of 33 files at r1, 7 of 10 files at r5, 2 of 6 files at r6, 3 of 5 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: all files reviewed, 1 unresolved discussion (waiting on @gsuess)

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: all files reviewed, 1 unresolved discussion (waiting on @vubogovich)

*[a discussion](https://reviewable.io/reviews/qualifyze/airtable-formulator/92#-NBwdNzq1VGs5JAzHhiD:-NC5_eis9WKDwGLG08Pb:b-896fix) (no related file):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Keeping this comment as blocking since `dev-people` was requested review as well and PR is on auto-merge. Feel free to discard it if thorough review is not needed.
</blockquote></details>

Done.

___

**Review by vubogovich — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gsuess)

**Pull request merged**
