### PR TITLE
Trigger test workflow on PR and other improvements from npm-package-template

### PR DESCRIPTION
**Pull request by vubogovich**
## What

Add a trigger to the test workflow to run on PR and other improvements from https://github.com/Qualifyze/npm-package-template

## Why

Unblock PRs raised from a forked repo like #83.

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/84)

### CODE REVIEW

**Review by sirJiggles — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/84)* status: all files reviewed, 4 unresolved discussions (waiting on @vubogovich)

___
*[.github/actions/check_integrity/action.yml, line 0 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQBDkA322BzSEZDicn:-MiQBDkA322BzSEZDico:bmsnjoz) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/actions/check_integrity/action.yml#L0)):*
ok, I see you do this now in the test job. How come it needed to be moved though?
___
*[.github/workflows/deploy.yml, line 21 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQC80I5N7cGpvvmK3-:-MiQC80I5N7cGpvvmK30:bvpdu4v) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/deploy.yml#L21)):*
> ```YAML
>         run: npm run build
>       - name: Run tests
>         run: npm run test
> ```

just curious, but do we need to test after merge? is it that two merged branches might not work together?
___
*[.github/workflows/deploy.yml, line 22 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQBqvO-OCuUfZhaN8w:-MiQBqvO-OCuUfZhaN8x:b5n5e8m) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/deploy.yml#L22)):*
> ```YAML
>       - name: Run tests
>         run: npm run test
>       - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
> ```

how come we needed to use this, does our own npm publish not work?
___
*[.github/workflows/deploy.yml, line 25 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQBgvtEAeZfGg2rinf:-MiQBgvtEAeZfGg2ring:b-seboz) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/deploy.yml#L25)):*
> ```YAML
>         with:
>           token: ${{ secrets.NPM_TOKEN }}
>       - uses: Klemensas/action-autotag@4d5bc0e2e8cf1b527a7bccdc84cf9314ae86a542
> ```

do we need auto tagging in this repo? it will make a new version on deploy right?

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
Great idea :100: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-:-MiQLseE3GmH9GdvwbH3:b45r8um)* status: all files reviewed, 6 unresolved discussions (waiting on @vubogovich)

___
*[.github/workflows/deploy.yml, line 4 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQLy20CHGQ7bhn9Xg1:-MiQLy20CHGQ7bhn9Xg2:bkd39ze) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/deploy.yml#L4)):*
> ```YAML
> on:
>   push:
>     branches: [ master ]
> ```

This reminds me we should rename the default branch to `main`
___
*[.github/workflows/test.yml, line 5 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQM9WLDxVLOqi10Nub:-MiQM9WLDxVLOqi10Nuc:bv3z4kg) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/test.yml#L5)):*
> ```YAML
>   push: { }
>   pull_request:
>     types: [ opened, synchronize ]
> ```

What's the reason to exclude `reopened` here? I would have expected the default to work just fine

**Review by vubogovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/84)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @gregoralbrecht, @sirJiggles, and @vubogovich)

___
*[.github/actions/check_integrity/action.yml, line  at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQBDkA322BzSEZDicn:-MiQYSdHEkWoDnXFd4FM:b-ynxmrd) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/actions/check_integrity/action.yml#L)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

ok, I see you do this now in the test job. How come it needed to be moved though?
</blockquote></details>

Because I switched it to `Qualifyze/check-git-integrity-action@v1.0.0`.
___
*[.github/workflows/deploy.yml, line 4 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQLy20CHGQ7bhn9Xg1:-MiQYfbJE_OBpjibp4IM:b51x57o) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/deploy.yml#L4)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This reminds me we should rename the default branch to `main`
</blockquote></details>

It's a topic for another PR.
___
*[.github/workflows/deploy.yml, line 21 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQC80I5N7cGpvvmK3-:-MiQlrPE982zXvJ3AV3a:bahxd52) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/deploy.yml#L21)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

just curious, but do we need to test after merge? is it that two merged branches might not work together?
</blockquote></details>

Just a safety measure in case the branch is temporary unprotected.
___
*[.github/workflows/deploy.yml, line 22 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQBqvO-OCuUfZhaN8w:-MiQm3ml9242nzdCwoZ9:b-c6l4ym) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/deploy.yml#L22)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

how come we needed to use this, does our own npm publish not work?
</blockquote></details>

We got our own fork for this action to reference it securely. However, it's simpler and safe to reference 3rd party actions with a commit hash.
___
*[.github/workflows/test.yml, line 5 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQM9WLDxVLOqi10Nub:-MiQknOs8CfYVMteRG4K:b3mxp89) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/test.yml#L5)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

What's the reason to exclude `reopened` here? I would have expected the default to work just fine
</blockquote></details>

Thanks for the catch. I thought all types are included by default :facepalm: 
Just for the reference https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
Remove explicit values.

**Review by vubogovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/84)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @gregoralbrecht and @sirJiggles)

___
*[.github/workflows/deploy.yml, line 25 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQBgvtEAeZfGg2rinf:-MiQpf3TDi-r6juXk0ek:b-7msra) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/deploy.yml#L25)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

do we need auto tagging in this repo? it will make a new version on deploy right?
</blockquote></details>

It's nice to get tags together with publish.

**Review by gregoralbrecht — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-:-MiQsP-C5osXLkL9aFi2:bnfp4nl)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht and @sirJiggles)

___
*[.github/workflows/deploy.yml, line 4 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQLy20CHGQ7bhn9Xg1:-MiQsB-GBtTGJL66f48q:bn0a6xc) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/deploy.yml#L4)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

It's a topic for another PR.
</blockquote></details>

Oops, that wasn't meant to be a blocking comment. My bad
___
*[.github/workflows/test.yml, line 5 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/84#-MiQM9WLDxVLOqi10Nub:-MiQsKfN0JzdFBbIVM7J:btojbfd) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/86a0a7b1f4dca56a2bcf60ab46812896e82f133b/.github/workflows/test.yml#L5)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Thanks for the catch. I thought all types are included by default :facepalm: 
Just for the reference https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
Remove explicit values.
</blockquote></details>

Great!

**Review by sirJiggles — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/84)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vubogovich)

**Pull request merged**
