### PR TITLE
Reverse parsing of airtable formulae 

### PR DESCRIPTION
**Pull request by gsuess**
# What❓

A parse function that converts string formulas to array notation formulas. (See readme)

# Why 💁‍♀️

Mainly to close the loop and have the ability to put the formulator into more rigorous e2e testing. The plan is to convert a string formula into array notation and then convert it back into a string formula a wide range of permutations.

# Todos before it can be reviewed

The things that need to be completed before this can be reviewed:

- [x] Merge #92

# Todos before it can be merged

The things that need to be completed before this PR can be merged:

None

### CODE REVIEW

**Comment by gsuess** [comment]
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/94)

**Review by vubogovich — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/94)* status: all files reviewed, 1 unresolved discussion (waiting on @gsuess)

*[a discussion](https://reviewable.io/reviews/qualifyze/airtable-formulator/94#-NC6ys2Z0Yax76nlbw32:-NC6ys2Z0Yax76nlbw33:b-rqeqkk) (no related file):*
It's a pleasure to read your code!

___
___
*[`src/parse.ts` line 106 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/94#-NC6y63q8IT0X5EXDT0i:-NC6y63q8IT0X5EXDT0j:bgopgnp) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/add941453ae7654757251283a789ed64ef7f402c/src/parse.ts#L106)):*
> ```XML
>     if (errors.length > 0) {
>       throw new Error(
>         `Invalid formula:\n ${errors.map((e) => e.message).join(", ")}\n`
> ```

It's weird to have LF at the end of exception. Maybe better to use it in `join`? If comma separated list, no need in both LFs here.
Easier to review if the case is covered with a test!

**Review by gsuess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/94)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @vubogovich)

*[a discussion](https://reviewable.io/reviews/qualifyze/airtable-formulator/94#-NC6ys2Z0Yax76nlbw32:-NCA4CHU9I_O_kVnoQtO:b2x9v3l) (no related file):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

It's a pleasure to read your code!
</blockquote></details>

:blush: 

___
___
*[`src/parse.ts` line 106 at r1](https://reviewable.io/reviews/qualifyze/airtable-formulator/94#-NC6y63q8IT0X5EXDT0i:-NCEV5GoDAh_k9_DM58a:b-896fix) ([raw file](https://github.com/qualifyze/airtable-formulator/blob/add941453ae7654757251283a789ed64ef7f402c/src/parse.ts#L106)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

It's weird to have LF at the end of exception. Maybe better to use it in `join`? If comma separated list, no need in both LFs here.
Easier to review if the case is covered with a test!
</blockquote></details>

Done.

**Review by vubogovich — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/airtable-formulator/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gsuess)

**Pull request merged**
